### ISSUE TITLE
i have reconstructed this project want to merge

### ISSUE THREAD

**Issue by ghost** [targos/gwt-api-exporter#2]
see https://github.com/LiaoSept/gwt-api-exporter/blob/master/src/index.js

**Comment by targos** [comment]
Hello. Thank you for your interest in this project!

Could you please open a PR so I can review your changes ?
And also make sure that the code can run at least on Node.js v4.x. We have corporate users that are stuck on LTS.

**Comment by ghost** [comment]
@targos

**Comment by ghost** [comment]
@targos ?
